variables:
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
sonarcloud-check:
  image: maven:3.6.3-jdk-11
  cache:
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar
  only:
    - merge_requests
    - master
    - develop
publish-artifact:
  image: maven:3.6.3-jdk-11
  cache:
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar
  
